### ISSUE TITLE
file selector in options

### ISSUE THREAD

**Issue by maboiteaspam** [iacopodeenosee/EasyScreenCast#21]
by default it s uninitialized, as a consequence the recording file path would not appear.
After click on a folder, it will appear, and the UI is updated to reflect a kind of initialization.

Would be great to make it intelligible out of the box.

--edit
in fact, it happens even after I selected a folder to save the videos.
BTW, i forgot, fedora@latest stable up2date on gnme3. Not sure which info i need to provide.

**Comment by iacopodeenosee** [comment]
hi, thank for your reports, in this case i explain the standard path in the tooltip show when mouse come over the two labels of that option, this is the message " if not specific a folder  the file will be saved in the $XDG_VIDEOS_DIR if it exists, or the home directory otherwise."
in this extension I used many tooltip to explain the options, I believe that in this way we get more clarity. 8y3
