### ISSUE TITLE
Update homepage link at extensions.gnome.org

### ISSUE THREAD

**Issue by kparal** [iacopodeenosee/EasyScreenCast#5]
Hello,

when I look at https://extensions.gnome.org/extension/690/easyscreencast/, the **Homepage** link refers to http://iacopodeenosee.wordpress.com/. But it's a bit difficult to find relevant information on a generic blog page. I think it would be much easier to point it either to the project homepage:
http://iacopodeenosee.wordpress.com/projects/easyscreencast/
or github itself:
https://github.com/iacopodeenosee/EasyScreenCast

People need this link mostly to contact the author and/or report problems, so one of those links would work much better.

Thanks!

**Comment by iacopodeenosee** [comment]
https://github.com/iacopodeenosee/EasyScreenCast/commit/36bdcd3fefed40c61764fb025f5b47a0029be6cc

**Comment by kparal** [comment]
It's interesting that this commit adds support for GNOME 3.14, but I installed EasyScreenCast from extensions.gnome.org in GNOME 3.14 some time ago.

Metadata says:
$ cat .local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/metadata.json 
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "This extension simplifies the use of the video recording function integrated in gnome shell, allows quickly to change the various settings of the desktop recording.", 
  "name": "EasyScreenCast", 
  "shell-version": [
    "3.12", 
    "3.14"
  ], 
  "url": "http://iacopodeenosee.wordpress.com/", 
  "uuid": "EasyScreenCast@iacopodeenosee.gmail.com", 
  "version": 13
}

So, in the extension installed from extensions.gnome.org, the `3.14` version is already there.

Also, the `version` is `13`, which is way above your `0.9.7`. What is this? Does this github repo have different contents than the one received from extensions.gnome.org? I'm utterly confused.

**Comment by iacopodeenosee** [comment]
in the git repo the file metadata.js wasn't update, my mistake; the "version" 13 is the number of revision pushed to the moderator of GSE(Gnome Shell Extension) site:
![schermata del 2015-01-07 10 58 08](https://cloud.githubusercontent.com/assets/4881584/5643748/60b9e73e-965c-11e4-8f8b-089d1cc8aa9d.png)
is not connected in any way to the version of the extension, the last version you can download from the GSE site is 0.9.6 update from this git repo at this commit https://github.com/iacopodeenosee/EasyScreenCast/commit/36198833cd6db827e092ab55dedfb76025aacbd3.
the next version of this extension is 0.9.7 and i'll uplouad it to GSE site when implement the audio support and i don't know now that revision number will, maybe 14 or 15 or 28...
depends on how many corrections I have to do because this is accepted

**Comment by kparal** [comment]
Interesting, so regardless of what `version` you have in your original `metadata.json`, after uploading it to extensions.gnome.org, it gets replaced by its own version number, right? That's a very weird design, it makes hard to mix extensions installed from git with extensions installed from GSE. But it explains everything, thanks for clarification.

**Comment by iacopodeenosee** [comment]
probably the developer should not even use the field VERSION into metadata.json, i don't know I remember a tutorial that used this field but made for GS version 3.1 or 3.2... very old stuff.
