### ISSUE TITLE
Error: No property show_all on this GObject GstDeviceMonitor

### ISSUE THREAD

**Issue by Acpinfo** [iacopodeenosee/EasyScreenCast#67]
The extension doesn't start and displays this message into the console : 

```
Error: No property show_all on this GObject GstDeviceMonitor

Stack trace:
  HelperWebcam<._init@/home/mei/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilwebcam.js:38
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
  EasyScreenCastSettingsWidget<._init@/home/mei/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:90
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  buildPrefsWidget@/home/mei/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:711
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1
```
  
This issue happens with the last release of EasyScreenCast (0.9.9) under Fedora 22 64bits Gnome 3.16.2. Works well under Fedora 23.

Note : commenting the line 38 of utilwebcam.js ( `  //         show_all: true`) allows me to open the parameters without the previous messages but still not the extension.

Do you have any idea how to pass this issue ?
Thank you.

**Comment by iacopodeenosee** [comment]
hi, i think the lib that i use to retreive the webcam and its caps is not compatible with gstreamer version of fedora 22, _which version of the gstreamer package is present on fedora 22?_ try this on terminal `gst-play-1.0 --gst-version` and paste here the result; it would be useful to have the ability to create documentation from .gir file of gstreamer, on arch this file you can find in this path /**usr/share/gir-1.0/Gst-1.0.gir** otherwise it searches for a file named Gst-1.0.gir

> Do you have any idea how to pass this issue ?

maybe you need to comment line **110** of file **extension.js** to exclude the loading section webcam, but this is a workaround. thx

**Comment by Acpinfo** [comment]
Hi,
- The output of `gst-play-1.0 --gst-version` is `GStreamer Core Library version 1.4.5` (and for info, 1.6.3 for Fedora 23).
- It's the same path as you mentioned for Gst-1.0.gir. Here it is :
[Gst-1.0.gir.zip](https://github.com/iacopodeenosee/EasyScreenCast/files/203022/Gst-1.0.gir.zip)
- The workaround works well (lines commented : #38 in utilwebcam.js and #110 for extension.js then Alt+F2 enter r).
Thank you very much!
