### ISSUE TITLE
Recording with Webcam doesn't work (creates a 0 bytes file)

### ISSUE THREAD

**Issue by nekohayo** [iacopodeenosee/EasyScreenCast#82]
Just for fun, tried to record with the webcam, after specifying the 800x600 video caps in easyscreencast's settings. Result: 0 bytes .webm files.

With debugging turned on, ```journalctl -f /usr/bin/gnome-session --since=15:15 |grep js``` returns nothing, and ```dbus-monitor "interface=org.gnome.Shell.Screencast"``` shows:

```
signal time=1462907777.842610 sender=org.freedesktop.DBus -> destination=:1.269 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.269"
signal time=1462907777.842744 sender=org.freedesktop.DBus -> destination=:1.269 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.269"

method call time=1462908094.670813 sender=:1.264 -> destination=:1.264 serial=505 path=/org/gnome/Shell/Screencast; interface=org.gnome.Shell.Screencast; member=ScreencastArea
   int32 551
   int32 329
   int32 903
   int32 473
   string "/home/jeff/Screencast_%d_%t.webm.webm"
   array [
      dict entry(
         string "draw-cursor"
         variant             boolean true
      )
      dict entry(
         string "framerate"
         variant             int32 10
      )
      dict entry(
         string "pipeline"
         variant             string "queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! videomixer name=mix sink_0::alpha=1 sink_1::alpha=0.75 sink_1::xpos=723 sink_1::ypos=426  ! videoconvert !  vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=%T ! mux. v4l2src device=/dev/video0 ! video/x-raw, format=YUY2, width=800, height=600, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=2:4:7:1, framerate={ 25/1, 20/1, 15/1, 10/1, 5/1 } ! videoscale ! video/x-raw, width=180, height=47,  add-borders=false ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mix. pulsesrc device="alsa_input.usb-AKM_AK5370-00.analog-mono" ! audioconvert ! vorbisenc ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. webmmux name=mux"
      )
   ]
method call time=1462908097.602490 sender=:1.264 -> destination=:1.264 serial=510 path=/org/gnome/Shell/Screencast; interface=org.gnome.Shell.Screencast; member=StopScreencast
```

Fedora 23, GNOME 3.18, GStreamer 1.6.4

**Comment by iacopodeenosee** [comment]
hi, to get logs you need to run **journalctl --since=today --no-pager | grep js** , i just updated the hint on the UI options, from what I see there must be a problem in webcam caps selected:

> ...v4l2src device=/dev/video0 ! video/x-raw, format=YUY2, width=800, height=600, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=2:4:7:1, **framerate={ 25/1, 20/1, 15/1, 10/1, 5/1 }**...

the framerate param seems invalid, I expect a single value, not an array of possibilities [like **framerate=25/1**], this seems strange to me, it would be useful the complete log to get ideas of how they made these caps.
if you want you can try this custom pipeline:
`queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! videomixer name=mix sink_0::alpha=1 sink_1::alpha=0.75 sink_1::xpos=723 sink_1::ypos=426  ! videoconvert !  vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=%T ! mux. v4l2src device=/dev/video0 ! video/x-raw, format=YUY2, width=800, height=600, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=2:4:7:1, framerate=25/1 ! videoscale ! video/x-raw, width=180, height=47,  add-borders=false ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mix. pulsesrc device="alsa_input.usb-AKM_AK5370-00.analog-mono" ! audioconvert ! vorbisenc ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mux. webmmux name=mux`

**Comment by chriseaton** [comment]
The webcam on my laptop is not working with easyscreencast either - it works ok with other webcam tools (guvcview, etc.). Like op the sudo journalctl /usr/bin/gnome-session --since=today --no-pager | grep js didn't return any results for me either.

I tried various different caps, none seemed to work. I also noticed the webcam light doesn't come on so it's likely not even getting to the initialization.

I'd be happy to help provide any logs to help get this to work!

**Comment by iacopodeenosee** [comment]
> The webcam on my laptop is not working with easyscreencast either - it works ok with other webcam tools (guvcview, etc.). Like op the sudo journalctl /usr/bin/gnome-session --since=today --no-pager | grep js didn't return any results for me either.

i think you need to enable the **verbose log** into option section of settings windows and after that try `journalctl --since=today --no-pager | grep js`

> I'd be happy to help provide any logs to help get this to work!

in addition to the **logs extension** put the result of the following commands:
- `v4l2-ctl --all`
- `for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done`
- `GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed`

paste here the result, which version of gnome-shell do you use? thx

**Comment by chriseaton** [comment]
Hi @iacopodeenosee,
      This is on a bleeding edge install - I'm running Gnome Shell 3.20.2 on Debian stretch (4.5.0-2-amd64 kernel).
_I've attached the log files ([logs.zip](https://github.com/iacopodeenosee/EasyScreenCast/files/286960/logs.zip))._

I also decided to follow the output from journalctl and I noticed this error popup (no "js"), but it happened right when I attempted to start recording:

- Gjs-Message: JS LOG: ESC>-%-setcallback TimerCounting called
- May 27 09:34:56 hero org.gnome.Shell.desktop[1277]: Gjs-Message: JS LOG: ESC>-*-update abs file path -> /home/chris/Videos/Screencast_05-27-2016_09:34:55 AM.webm.webm
- May 27 09:34:56 hero org.gnome.Shell.desktop[1277]: Gjs-Message: JS LOG: ESC>-*-refresh indicator -A true -F undefined
- **May 27 09:34:56 hero org.gnome.Shell.desktop[1277]: ** (gnome-shell:1277): WARNING **: Error in recording pipeline: Internal data flow error.**
- May 27 09:34:57 hero org.gnome.Shell.desktop[1277]: Gjs-Message: JS LOG: ESC>-%-continued TimerCounting | sec: 1
- May 27 09:34:58 hero org.gnome.Shell.desktop[1277]: Gjs-Message: JS LOG: ESC>-%-continued TimerCounting | sec: 2
- May 27 09:34:59 hero org.gnome.Shell.desktop[1277]: Gjs-Message: JS LOG: ESC>-%-continued TimerCounting | sec: 3
- May 27 09:34:59 hero org.gnome.Shell.desktop[1277]: Gjs-Message: JS LOG: ESC>-*-refresh indicator -A true -F true

Also I just want to say - thanks for this awesome tool - screen recording works great.

**Comment by chriseaton** [comment]
Hey @iacopodeenosee - So... I'm an idiot - I just tried one of the cap options (with format=RGB) and it worked! If someone else comes around with a similar issue I guess you can point them to this thread :)

Apparently my webcam _only_ works with RGB formats (any other cap formats like YUV2 fail).

**Comment by iacopodeenosee** [comment]
@chriseaton  it's strange every caps must be working...these caps are given by the webcam as compatible... can you please try that on terminal?
`gst-launch-1.0  --gst-debug=3 ximagesrc queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! videomixer name=mix sink_0::alpha=1 sink_1::alpha=0.75 sink_1::xpos=1536 sink_1::ypos=972  ! videoconvert !  vp8enc min_quantizer=4 max_quantizer=13 cpu-used=2 deadline=500000 sharpness=0 target-bitrate=15000 threads=%T ! mux. v4l2src device=/dev/video0 ! video/x-raw, format=YUY2, width=320, height=240, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=2:4:7:1, framerate=30/1 ! videoscale ! video/x-raw, width=384, height=108, add-borders=false ! queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! mix. webmmux name=mux`

this command try to cacth screen with a **bad caps webcam** stream, the execution will return an error? thx
