### ISSUE TITLE
Possible versioning problem (release 0.9.9)

### ISSUE THREAD

**Issue by samueloph** [iacopodeenosee/EasyScreenCast#99]
[This commit](https://github.com/iacopodeenosee/EasyScreenCast/commit/4dddce3a5e91ded04ee993616346464c14af7f5d) changes metadata.json's version to "0.9.9", then the following releases were made: 
* 0.9.8.1
* 0.9.8.2
* 0.9.8.3
* 0.9.8.4
* 0.9.8.5

All of them marked as 0.9.9.

Wouldn't be better to adjust metadata.json to the correct version? Doesn't this cause problems with detecting the current version when upgrading? (eg. using extensions.gnome.org)

**Comment by iacopodeenosee** [comment]
hi, the field **version** is automatically overwritten by the GSE site with a sequence number that complies with the upload number, [Now this number for ESC is the 33.](https://extensions.gnome.org/review/download/6028.shell-extension.zip)
so if you have installed the extension from the site GSE the failed update is not due to that, and if you have installed the extension from GIT repo or by a packet manager in the GSE not any updates since the version number is not valid will be notified, but it is to be checked.
